name: Build Android APK

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch: # Permite ejecutar la compilación de forma manual desde la web de GitHub

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Como el proyecto de Android está dentro de Qntrol_App, le decimos a las acciones
      # que busquen los archivos allí usando working-directory
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: Qntrol_App

      - name: Build Debug APK
        run: ./gradlew assembleDebug
        working-directory: Qntrol_App

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: QntrolApp-Debug-APK
          path: Qntrol_App/app/build/outputs/apk/debug/app-debug.apk
